application: delicious-export-hrd
version: 3
runtime: python
api_version: 1

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /(.*\.(html|js))
  static_files: static/\1
  upload: static/(.*\.(html|js))

- url: .*
  script: main.py

builtins:
- appstats: on
